### ISSUE TITLE
Ability to list all comments, even if place where they were made is gone

### ISSUE THREAD

**Issue by jumper047** [masukomi/private_comments#19]
Love your app, but inability to check comments I wrote before without playing with revisions is very inconvenient for me. Is it possible to add something like list of the all comments for file/project?
I use Private Comments with Emacs, if it matters

**Comment by masukomi** [comment]
Sorry i didn't see this. I've apparently missed a bunch of comments here. (ironic) 

🤔  It actually already supports this. From [the api docs](https://masukomi.github.io/private_comments/#retrieve-comments-for-a-file-endpoint) 

You just need to pass it a list of all the treeishes that that file has ever had. 

basically, take the output of `git log --pretty='format:%H' path/to/file` concatenate it as a comma separated list and append it to the end of the get request for the file in question like this  `&treeshes=hash1,hash2,hash3`

This is how it normally functions, the only difference is that NORMALLY it's only sending a list of the treeishes from commits whose code still remains untouched in the file. These are the treeishes you'd see if you ran `git blame` on the file. 

Apologies for the delay. But, this is "just" a matter of hacking the plugin code to display the output in a separate buffer in a way that's useful. Probably you'd want to take the list of hashes it returns and start querying git about who made them and when and then do something like

```
comments on path/to/foo.rb

jumper047: Nov 22, 2022
Love your app, but inability to check comments I wrote before without playing with revisions is very inconvenient for me. Is it possible to add something like list of the all comments for file/project?...
<relevant code snippet here>


masukomi: Oct 26, 2023
🤦‍♀️ i need to get better at github notifications
<relevant code snippet here>
````

**Comment by masukomi** [comment]
Closing this because it's already supported here on the server side. I don't have the emacs chops to make this happen in the [emacs plugin](https://github.com/masukomi/private-comments-mode) but i would happily accept PRs if you (or anyone else) feels like making this happen.
